# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FamilyTV' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'AlamofireImage'
  use_frameworks!

  # Pods for FamilyTV

end

target 'TopShelf' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TopShelf

end
